//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.11 at 11:06:16 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://raw.githubusercontent.com/nalet/bfh/master/bti7055p/LottoTool/ticketType", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ch.bti7055p.calculations;
